## CEBD 1260 Introduction to big data and machine learning

## Session 2: General methodologies in machine learning

in this notebook, we will practice general methods of machine learning 

NOTE: for each activity below, please refer and correspond with our course slides

Instructor: Yimin Nie

email: ymnie888@gmail.com

#### Submission of your assignments:

each assignment is given in this notebook, please complete them by creating another jupyter notebook and submit on dropbox

## import important libs

In [2]:
import numpy as np   # import numpy
import pandas as pd  # import pandas
import os
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

## Activity 1:  read your data, split input and target variables for your data

In [4]:
# DATA_PATH
# DATA_PATH = r'C:\Users\enxxmnx\OneDrive - Ericsson AB\workspace\training\data\city_bike_share'
# DATA_PATH = r'C:\\Users\\enxxmnx\\OneDrive - Ericsson AB\\workspace\\training\\data\\city_bike_share' # this is also working
DATA_PATH = r'C:\Users\bpare\Desktop\CEBD 1260'

In [6]:
df = pd.read_csv((DATA_PATH+r'\home_credit_risk\home-credit-default-risk\application_train.csv'))
# df = pd.read_csv(os.path.join(DATA_PATH,'train.csv'))
df.head()

SK_ID_CURR  TARGET NAME_CONTRACT_TYPE CODE_GENDER FLAG_OWN_CAR  \
0      100002       1         Cash loans           M            N   
1      100003       0         Cash loans           F            N   
2      100004       0    Revolving loans           M            Y   
3      100006       0         Cash loans           F            N   
4      100007       0         Cash loans           M            N   

  FLAG_OWN_REALTY  CNT_CHILDREN  AMT_INCOME_TOTAL  AMT_CREDIT  AMT_ANNUITY  \
0               Y             0          202500.0    406597.5      24700.5   
1               N             0          270000.0   1293502.5      35698.5   
2               Y             0           67500.0    135000.0       6750.0   
3               Y             0          135000.0    312682.5      29686.5   
4               Y             0          121500.0    513000.0      21865.5   

   ...  FLAG_DOCUMENT_18 FLAG_DOCUMENT_19 FLAG_DOCUMENT_20 FLAG_DOCUMENT_21  \
0  ...                 0                0                0                0   
1  ...                 0                0                0                0   
2  ...                 0                0                0                0   
3  ...                 0                0                0                0   
4  ...                 0                0                0                0   

  AMT_REQ_CREDIT_BUREAU_HOUR AMT_REQ_CREDIT_BUREAU_DAY  \
0                        0.0                       0.0   
1                        0.0                       0.0   
2                        0.0                       0.0   
3                        NaN                       NaN   
4                        0.0                       0.0   

   AMT_REQ_CREDIT_BUREAU_WEEK  AMT_REQ_CREDIT_BUREAU_MON  \
0                         0.0                        0.0   
1                         0.0                        0.0   
2                         0.0                        0.0   
3                         NaN                        NaN   
4                         0.0                        0.0   

   AMT_REQ_CREDIT_BUREAU_QRT  AMT_REQ_CREDIT_BUREAU_YEAR  
0                        0.0                         1.0  
1                        0.0                         0.0  
2                        0.0                         0.0  
3                        NaN                         NaN  
4                        0.0                         0.0  

[5 rows x 122 columns]

In [7]:
#get some info from data frame
print(df.shape)

(307511, 122)


In [8]:
# check the data 
df.head()
# df.head(3)
# df.tail()

SK_ID_CURR  TARGET NAME_CONTRACT_TYPE CODE_GENDER FLAG_OWN_CAR  \
0      100002       1         Cash loans           M            N   
1      100003       0         Cash loans           F            N   
2      100004       0    Revolving loans           M            Y   
3      100006       0         Cash loans           F            N   
4      100007       0         Cash loans           M            N   

  FLAG_OWN_REALTY  CNT_CHILDREN  AMT_INCOME_TOTAL  AMT_CREDIT  AMT_ANNUITY  \
0               Y             0          202500.0    406597.5      24700.5   
1               N             0          270000.0   1293502.5      35698.5   
2               Y             0           67500.0    135000.0       6750.0   
3               Y             0          135000.0    312682.5      29686.5   
4               Y             0          121500.0    513000.0      21865.5   

   ...  FLAG_DOCUMENT_18 FLAG_DOCUMENT_19 FLAG_DOCUMENT_20 FLAG_DOCUMENT_21  \
0  ...                 0                0                0                0   
1  ...                 0                0                0                0   
2  ...                 0                0                0                0   
3  ...                 0                0                0                0   
4  ...                 0                0                0                0   

  AMT_REQ_CREDIT_BUREAU_HOUR AMT_REQ_CREDIT_BUREAU_DAY  \
0                        0.0                       0.0   
1                        0.0                       0.0   
2                        0.0                       0.0   
3                        NaN                       NaN   
4                        0.0                       0.0   

   AMT_REQ_CREDIT_BUREAU_WEEK  AMT_REQ_CREDIT_BUREAU_MON  \
0                         0.0                        0.0   
1                         0.0                        0.0   
2                         0.0                        0.0   
3                         NaN                        NaN   
4                         0.0                        0.0   

   AMT_REQ_CREDIT_BUREAU_QRT  AMT_REQ_CREDIT_BUREAU_YEAR  
0                        0.0                         1.0  
1                        0.0                         0.0  
2                        0.0                         0.0  
3                        NaN                         NaN  
4                        0.0                         0.0  

[5 rows x 122 columns]

In [6]:
df.info() # this give you more infor about data type of each column

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10886 entries, 0 to 10885
Data columns (total 12 columns):
datetime      10886 non-null object
season        10886 non-null int64
holiday       10886 non-null int64
workingday    10886 non-null int64
weather       10886 non-null int64
temp          10886 non-null float64
atemp         10886 non-null float64
humidity      10886 non-null int64
windspeed     10886 non-null float64
casual        10886 non-null int64
registered    10886 non-null int64
count         10886 non-null int64
dtypes: float64(3), int64(8), object(1)
memory usage: 1020.7+ KB


In [9]:
des = df.describe() # describe the statistical property of the data
des

SK_ID_CURR         TARGET   CNT_CHILDREN  AMT_INCOME_TOTAL  \
count  307511.000000  307511.000000  307511.000000      3.075110e+05   
mean   278180.518577       0.080729       0.417052      1.687979e+05   
std    102790.175348       0.272419       0.722121      2.371231e+05   
min    100002.000000       0.000000       0.000000      2.565000e+04   
25%    189145.500000       0.000000       0.000000      1.125000e+05   
50%    278202.000000       0.000000       0.000000      1.471500e+05   
75%    367142.500000       0.000000       1.000000      2.025000e+05   
max    456255.000000       1.000000      19.000000      1.170000e+08   

         AMT_CREDIT    AMT_ANNUITY  AMT_GOODS_PRICE  \
count  3.075110e+05  307499.000000     3.072330e+05   
mean   5.990260e+05   27108.573909     5.383962e+05   
std    4.024908e+05   14493.737315     3.694465e+05   
min    4.500000e+04    1615.500000     4.050000e+04   
25%    2.700000e+05   16524.000000     2.385000e+05   
50%    5.135310e+05   24903.000000     4.500000e+05   
75%    8.086500e+05   34596.000000     6.795000e+05   
max    4.050000e+06  258025.500000     4.050000e+06   

       REGION_POPULATION_RELATIVE     DAYS_BIRTH  DAYS_EMPLOYED  ...  \
count               307511.000000  307511.000000  307511.000000  ...   
mean                     0.020868  -16036.995067   63815.045904  ...   
std                      0.013831    4363.988632  141275.766519  ...   
min                      0.000290  -25229.000000  -17912.000000  ...   
25%                      0.010006  -19682.000000   -2760.000000  ...   
50%                      0.018850  -15750.000000   -1213.000000  ...   
75%                      0.028663  -12413.000000    -289.000000  ...   
max                      0.072508   -7489.000000  365243.000000  ...   

       FLAG_DOCUMENT_18  FLAG_DOCUMENT_19  FLAG_DOCUMENT_20  FLAG_DOCUMENT_21  \
count     307511.000000     307511.000000     307511.000000     307511.000000   
mean           0.008130          0.000595          0.000507          0.000335   
std            0.089798          0.024387          0.022518          0.018299   
min            0.000000          0.000000          0.000000          0.000000   
25%            0.000000          0.000000          0.000000          0.000000   
50%            0.000000          0.000000          0.000000          0.000000   
75%            0.000000          0.000000          0.000000          0.000000   
max            1.000000          1.000000          1.000000          1.000000   

       AMT_REQ_CREDIT_BUREAU_HOUR  AMT_REQ_CREDIT_BUREAU_DAY  \
count               265992.000000              265992.000000   
mean                     0.006402                   0.007000   
std                      0.083849                   0.110757   
min                      0.000000                   0.000000   
25%                      0.000000                   0.000000   
50%                      0.000000                   0.000000   
75%                      0.000000                   0.000000   
max                      4.000000                   9.000000   

       AMT_REQ_CREDIT_BUREAU_WEEK  AMT_REQ_CREDIT_BUREAU_MON  \
count               265992.000000              265992.000000   
mean                     0.034362                   0.267395   
std                      0.204685                   0.916002   
min                      0.000000                   0.000000   
25%                      0.000000                   0.000000   
50%                      0.000000                   0.000000   
75%                      0.000000                   0.000000   
max                      8.000000                  27.000000   

       AMT_REQ_CREDIT_BUREAU_QRT  AMT_REQ_CREDIT_BUREAU_YEAR  
count              265992.000000               265992.000000  
mean                    0.265474                    1.899974  
std                     0.794056                    1.869295  
min                     0.000000                    0.000000  
25%              

In [11]:
# get input and target from your data, X is the input, y is the target
y = df['AMT_ANNUITY'].values# define target 
y

array([24700.5, 35698.5,  6750. , ..., 29979. , 20205. , 49117.5])

In [12]:
# get a full list of features we will use for input
features = [f for f in df.columns.values if f not in ['FLAG_DOCUMENT_18','FLAG_DOCUMENT_20']] 
print(features)

['SK_ID_CURR', 'TARGET', 'NAME_CONTRACT_TYPE', 'CODE_GENDER', 'FLAG_OWN_CAR', 'FLAG_OWN_REALTY', 'CNT_CHILDREN', 'AMT_INCOME_TOTAL', 'AMT_CREDIT', 'AMT_ANNUITY', 'AMT_GOODS_PRICE', 'NAME_TYPE_SUITE', 'NAME_INCOME_TYPE', 'NAME_EDUCATION_TYPE', 'NAME_FAMILY_STATUS', 'NAME_HOUSING_TYPE', 'REGION_POPULATION_RELATIVE', 'DAYS_BIRTH', 'DAYS_EMPLOYED', 'DAYS_REGISTRATION', 'DAYS_ID_PUBLISH', 'OWN_CAR_AGE', 'FLAG_MOBIL', 'FLAG_EMP_PHONE', 'FLAG_WORK_PHONE', 'FLAG_CONT_MOBILE', 'FLAG_PHONE', 'FLAG_EMAIL', 'OCCUPATION_TYPE', 'CNT_FAM_MEMBERS', 'REGION_RATING_CLIENT', 'REGION_RATING_CLIENT_W_CITY', 'WEEKDAY_APPR_PROCESS_START', 'HOUR_APPR_PROCESS_START', 'REG_REGION_NOT_LIVE_REGION', 'REG_REGION_NOT_WORK_REGION', 'LIVE_REGION_NOT_WORK_REGION', 'REG_CITY_NOT_LIVE_CITY', 'REG_CITY_NOT_WORK_CITY', 'LIVE_CITY_NOT_WORK_CITY', 'ORGANIZATION_TYPE', 'EXT_SOURCE_1', 'EXT_SOURCE_2', 'EXT_SOURCE_3', 'APARTMENTS_AVG', 'BASEMENTAREA_AVG', 'YEARS_BEGINEXPLUATATION_AVG', 'YEARS_BUILD_AVG', 'COMMONAREA_AVG', 'ELE

In [14]:
X = df["AMT_CREDIT"] # get X

In [15]:
print(X.shape,len(y))

(307511,) 307511


In [17]:
X.head(307511)

0          406597.5
1         1293502.5
2          135000.0
3          312682.5
4          513000.0
5          490495.5
6         1560726.0
7         1530000.0
8         1019610.0
9          405000.0
10         652500.0
11         148365.0
12          80865.0
13         918468.0
14         773680.5
15         299772.0
16         509602.5
17         270000.0
18         157500.0
19         544491.0
20         427500.0
21        1132573.5
22         497520.0
23         239850.0
24         247500.0
25         225000.0
26         979992.0
27         327024.0
28         790830.0
29         180000.0
            ...    
307481     297000.0
307482     500566.5
307483     247275.0
307484     545040.0
307485     180000.0
307486     355536.0
307487    1071909.0
307488     135000.0
307489     521280.0
307490     135000.0
307491    1078200.0
307492    1575000.0
307493     946764.0
307494     479700.0
307495     808650.0
307496     337500.0
307497     270126.0
307498    1312110.0
307499     225000.0


#### Assignment 1: 

please read and split input and output for your own project data and understanding in details

## Activity 2:  identify categorical and numerical features 

In [18]:
# print data type for each feature
for f in features:
    print(" {}: {}".format(f,df[f].dtype))

 SK_ID_CURR: int64
 TARGET: int64
 NAME_CONTRACT_TYPE: object
 CODE_GENDER: object
 FLAG_OWN_CAR: object
 FLAG_OWN_REALTY: object
 CNT_CHILDREN: int64
 AMT_INCOME_TOTAL: float64
 AMT_CREDIT: float64
 AMT_ANNUITY: float64
 AMT_GOODS_PRICE: float64
 NAME_TYPE_SUITE: object
 NAME_INCOME_TYPE: object
 NAME_EDUCATION_TYPE: object
 NAME_FAMILY_STATUS: object
 NAME_HOUSING_TYPE: object
 REGION_POPULATION_RELATIVE: float64
 DAYS_BIRTH: int64
 DAYS_EMPLOYED: int64
 DAYS_REGISTRATION: float64
 DAYS_ID_PUBLISH: int64
 OWN_CAR_AGE: float64
 FLAG_MOBIL: int64
 FLAG_EMP_PHONE: int64
 FLAG_WORK_PHONE: int64
 FLAG_CONT_MOBILE: int64
 FLAG_PHONE: int64
 FLAG_EMAIL: int64
 OCCUPATION_TYPE: object
 CNT_FAM_MEMBERS: float64
 REGION_RATING_CLIENT: int64
 REGION_RATING_CLIENT_W_CITY: int64
 WEEKDAY_APPR_PROCESS_START: object
 HOUR_APPR_PROCESS_START: int64
 REG_REGION_NOT_LIVE_REGION: int64
 REG_REGION_NOT_WORK_REGION: int64
 LIVE_REGION_NOT_WORK_REGION: int64
 REG_CITY_NOT_LIVE_CITY: int64
 REG_CITY_NOT_WO

In [19]:
#pickup all features what are categorical
cat_features = []
for f in features:
    if str(df[f].dtype) == 'object':
        cat_features.append(f)
print(cat_features)

['NAME_CONTRACT_TYPE', 'CODE_GENDER', 'FLAG_OWN_CAR', 'FLAG_OWN_REALTY', 'NAME_TYPE_SUITE', 'NAME_INCOME_TYPE', 'NAME_EDUCATION_TYPE', 'NAME_FAMILY_STATUS', 'NAME_HOUSING_TYPE', 'OCCUPATION_TYPE', 'WEEKDAY_APPR_PROCESS_START', 'ORGANIZATION_TYPE', 'FONDKAPREMONT_MODE', 'HOUSETYPE_MODE', 'WALLSMATERIAL_MODE', 'EMERGENCYSTATE_MODE']


DISCUSSIN: is it true above?? what are categorical features you think?

In [20]:
# sometimes we need to really see if one feature is categorical based on our domain knowledge or common sense
cat_features = []
for f in features:
    if str(df[f].dtype) in ['object','int64']:
        cat_features.append(f)
print(cat_features)

['SK_ID_CURR', 'TARGET', 'NAME_CONTRACT_TYPE', 'CODE_GENDER', 'FLAG_OWN_CAR', 'FLAG_OWN_REALTY', 'CNT_CHILDREN', 'NAME_TYPE_SUITE', 'NAME_INCOME_TYPE', 'NAME_EDUCATION_TYPE', 'NAME_FAMILY_STATUS', 'NAME_HOUSING_TYPE', 'DAYS_BIRTH', 'DAYS_EMPLOYED', 'DAYS_ID_PUBLISH', 'FLAG_MOBIL', 'FLAG_EMP_PHONE', 'FLAG_WORK_PHONE', 'FLAG_CONT_MOBILE', 'FLAG_PHONE', 'FLAG_EMAIL', 'OCCUPATION_TYPE', 'REGION_RATING_CLIENT', 'REGION_RATING_CLIENT_W_CITY', 'WEEKDAY_APPR_PROCESS_START', 'HOUR_APPR_PROCESS_START', 'REG_REGION_NOT_LIVE_REGION', 'REG_REGION_NOT_WORK_REGION', 'LIVE_REGION_NOT_WORK_REGION', 'REG_CITY_NOT_LIVE_CITY', 'REG_CITY_NOT_WORK_CITY', 'LIVE_CITY_NOT_WORK_CITY', 'ORGANIZATION_TYPE', 'FONDKAPREMONT_MODE', 'HOUSETYPE_MODE', 'WALLSMATERIAL_MODE', 'EMERGENCYSTATE_MODE', 'FLAG_DOCUMENT_2', 'FLAG_DOCUMENT_3', 'FLAG_DOCUMENT_4', 'FLAG_DOCUMENT_5', 'FLAG_DOCUMENT_6', 'FLAG_DOCUMENT_7', 'FLAG_DOCUMENT_8', 'FLAG_DOCUMENT_9', 'FLAG_DOCUMENT_10', 'FLAG_DOCUMENT_11', 'FLAG_DOCUMENT_12', 'FLAG_DOCUMENT

#### Assignment 2: 

please identify categorical features for your own data, you need to use some coding and your own understanding from the data

## Activity 3:  split total data by train, test and validation

In [21]:
from sklearn.model_selection import train_test_split

In [22]:
# split 20% data as test data
train_X,test_X,train_y,test_y = train_test_split(X,y,shuffle=True,random_state=2019,test_size=0.2)
print(train_X.shape,test_X.shape,len(train_y),len(test_y))

(246008,) (61503,) 246008 61503


In [23]:
# split another 20% data as valid data, NOTE that you cannot touch test data again
train_X,valid_X,train_y,valid_y = train_test_split(train_X,train_y,shuffle=True,random_state=668,test_size=0.2)
print(train_X.shape,valid_X.shape,len(train_y),len(valid_y))

(196806,) (49202,) 196806 49202


#### Assignment 3: 

please split your own project data train,valid,test by 20%,25% from the total data set

## Activity 4: split overall data set using cross validation strategies

In [24]:
from sklearn.model_selection import KFold,StratifiedKFold

In [25]:
kf = KFold(n_splits=5)
for train_idx,valid_idx in kf.split(X,y):
    print(train_idx,valid_idx)

[ 61503  61504  61505 ... 307508 307509 307510] [    0     1     2 ... 61500 61501 61502]
[     0      1      2 ... 307508 307509 307510] [ 61503  61504  61505 ... 123002 123003 123004]
[     0      1      2 ... 307508 307509 307510] [123005 123006 123007 ... 184504 184505 184506]
[     0      1      2 ... 307508 307509 307510] [184507 184508 184509 ... 246006 246007 246008]
[     0      1      2 ... 246006 246007 246008] [246009 246010 246011 ... 307508 307509 307510]


In [26]:
for train_idx,valid_idx in kf.split(X,y):
    train_X = X.loc[train_idx]
    train_y = y[train_idx]
    
    valid_X = X.loc[valid_idx]
    valid_y = y[valid_idx]

#### Assignment 4: 

practice cross validation split by your own data

## Activity 5: practice different loss functions provided by sklearn toolkit


In [27]:
from sklearn.metrics import mean_absolute_error,mean_squared_error,log_loss

In [33]:
x = [0.4,0.7,1.5,2.9]
x_hat = [0.3,0.67,1.6,2.87]
mean_absolute_error(x,x_hat)

0.06499999999999996

In [40]:
x=[1,0,1,0,0,0,1,1,0,0,0]
x_hat =[0.98,0.12,0.86,0.04,0.004,0.01,0.998,0.976,0.005,0.025,0.017]
log_loss(x,x_hat)

0.0388645931105278

#### Assignment 5: 

refer the math defination of loss function in our slides and try to understand how to code them in sklearn